"""esquema inicial com modulos

Revision ID: 0001_esquema_inicial
Revises: 
Create Date: 2026-09-30 17:21:41.951180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_esquema_inicial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('rotulo_controle', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modulo')),
    sa.UniqueConstraint('codigo', name=op.f('uq_modulo_codigo'))
    )
    op.create_table('regime_tributario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regime_tributario')),
    sa.UniqueConstraint('nome', name=op.f('uq_regime_tributario_nome'))
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsavel'))
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['regime_id'], ['regime_tributario.id'], name=op.f('fk_empresa_regime_id_regime_tributario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_empresa_cnpj'))
    )
    op.create_table('obrigacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('periodicidade', sa.String(length=20), nullable=False),
    sa.Column('esfera', sa.String(length=20), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], name=op.f('fk_obrigacao_modulo_id_modulo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obrigacao')),
    sa.UniqueConstraint('modulo_id', 'nome', name=op.f('uq_obrigacao_modulo_id_nome'))
    )
    op.create_table('empresa_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('concluido_ate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_empresa_modulo_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], name=op.f('fk_empresa_modulo_modulo_id_modulo')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_empresa_modulo_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa_modulo')),
    sa.UniqueConstraint('empresa_id', 'modulo_id', name=op.f('uq_empresa_modulo_empresa_id_modulo_id'))
    )
    op.create_table('empresa_obrigacao_ajuste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('obrigacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_empresa_obrigacao_ajuste_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['obrigacao_id'], ['obrigacao.id'], name=op.f('fk_empresa_obrigacao_ajuste_obrigacao_id_obrigacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa_obrigacao_ajuste')),
    sa.UniqueConstraint('empresa_id', 'obrigacao_id', name=op.f('uq_empresa_obrigacao_ajuste_empresa_id_obrigacao_id'))
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('obrigacao_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_entrega_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['obrigacao_id'], ['obrigacao.id'], name=op.f('fk_entrega_obrigacao_id_obrigacao')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], name=op.f('fk_entrega_responsavel_id_responsavel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrega')),
    sa.UniqueConstraint('empresa_id', 'obrigacao_id', 'competencia', name=op.f('uq_entrega_empresa_id_obrigacao_id_competencia'))
    )
    op.create_table('regime_obrigacao',
    sa.Column('regime_id', sa.Integer(), nullable=False),
    sa.Column('obrigacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['obrigacao_id'], ['obrigacao.id'], name=op.f('fk_regime_obrigacao_obrigacao_id_obrigacao')),
    sa.ForeignKeyConstraint(['regime_id'], ['regime_tributario.id'], name=op.f('fk_regime_obrigacao_regime_id_regime_tributario')),
    sa.PrimaryKeyConstraint('regime_id', 'obrigacao_id', name=op.f('pk_regime_obrigacao'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regime_obrigacao')
    op.drop_table('entrega')
    op.drop_table('empresa_obrigacao_ajuste')
    op.drop_table('empresa_modulo')
    op.drop_table('obrigacao')
    op.drop_table('empresa')
    op.drop_table('responsavel')
    op.drop_table('regime_tributario')
    op.drop_table('modulo')
    # ### end Alembic commands ###
