"""codigo da empresa

Revision ID: 0003_codigo_empresa
Revises: 0002_usuarios
Create Date: 2026-09-30 18:04:27.124043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_codigo_empresa'
down_revision = '0002_usuarios'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_empresa_codigo'), ['codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_codigo'))
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
