"""socios e distribuicao de lucros

Revision ID: 0004_socios_distribuicao
Revises: 0003_codigo_empresa
Create Date: 2026-09-30 21:43:09.336718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004_socios_distribuicao'
down_revision = '0003_codigo_empresa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_socio_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_socio')),
    sa.UniqueConstraint('empresa_id', 'documento', name=op.f('uq_socio_empresa_id_documento'))
    )
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_socio_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('distribuicao_lucro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], name=op.f('fk_distribuicao_lucro_socio_id_socio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distribuicao_lucro')),
    sa.UniqueConstraint('socio_id', 'ano', 'mes', name=op.f('uq_distribuicao_lucro_socio_id_ano_mes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribuicao_lucro')
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_socio_empresa_id'))

    op.drop_table('socio')
    # ### end Alembic commands ###
