"""percentual de quotas do socio

Revision ID: 0005_quotas_socio
Revises: 0004_socios_distribuicao
Create Date: 2026-09-30 22:17:12.570455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005_quotas_socio'
down_revision = '0004_socios_distribuicao'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual', sa.Numeric(precision=6, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('percentual')

    # ### end Alembic commands ###
