"""grupo economico

Revision ID: 0006_grupo_economico
Revises: 0005_quotas_socio
Create Date: 2026-10-01 17:35:19.275430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006_grupo_economico'
down_revision = '0005_quotas_socio'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_economico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo_economico')),
    sa.UniqueConstraint('nome', name=op.f('uq_grupo_economico_nome'))
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_empresa_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_empresa_grupo_id_grupo_economico'), 'grupo_economico', ['grupo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_empresa_grupo_id_grupo_economico'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_empresa_grupo_id'))
        batch_op.drop_column('grupo_id')

    op.drop_table('grupo_economico')
    # ### end Alembic commands ###
