"""obrigacoes contabeis e imposto

Revision ID: 0007_obrigacoes_imposto
Revises: 0006_grupo_economico
Create Date: 2026-10-01 18:44:52.876804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007_obrigacoes_imposto'
down_revision = '0006_grupo_economico'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('valor_imposto', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_quota', sa.Numeric(precision=14, scale=2), nullable=True))

    with op.batch_alter_table('obrigacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controla_imposto', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###
    reparametrizar_contabil()


# Obrigações do módulo Contábil por tributação (pedido do escritório, out/2026).
# Regimes não listados (MEI, Imune/Isenta, A definir) ficam como estão.
OBRIGACOES = {
    "ECD": ("anual", "Escrituração Contábil Digital (SPED Contábil)", False),
    "ECF": ("anual", "Escrituração Contábil Fiscal", False),
    "DEFIS": ("anual", "Declaração de informações socioeconômicas e fiscais", False),
    "IRPJ": ("trimestral", "Apuração e recolhimento do IRPJ (quota única ou parcelado)", True),
    "CSLL": ("trimestral", "Apuração e recolhimento da CSLL (quota única ou parcelado)", True),
}
POR_REGIME = {
    "Lucro Real": ["ECD", "ECF", "IRPJ", "CSLL"],
    "Lucro Real Trimestral": ["ECD", "ECF", "IRPJ", "CSLL"],
    "Lucro Presumido": ["ECD", "ECF"],
    "Simples Nacional": ["ECD", "DEFIS"],
}


def reparametrizar_contabil():
    """Ajusta os vínculos regime × obrigação do Contábil em bancos já existentes.

    Em banco novo (ainda sem módulos) não faz nada: os dados iniciais já vêm assim.
    """
    con = op.get_bind()
    modulo = con.execute(sa.text("SELECT id FROM modulo WHERE codigo = 'contabil'")).scalar()
    if modulo is None:
        return
    ids = {}
    for nome, (periodicidade, descricao, imposto) in OBRIGACOES.items():
        oid = con.execute(sa.text("SELECT id FROM obrigacao WHERE modulo_id = :m AND nome = :n"),
                          {"m": modulo, "n": nome}).scalar()
        if oid is None:
            con.execute(sa.text(
                "INSERT INTO obrigacao (modulo_id, nome, descricao, periodicidade, esfera, ativo, controla_imposto) "
                "VALUES (:m, :n, :d, :p, 'federal', :t, :i)"),
                {"m": modulo, "n": nome, "d": descricao, "p": periodicidade, "t": True, "i": imposto})
            oid = con.execute(sa.text("SELECT id FROM obrigacao WHERE modulo_id = :m AND nome = :n"),
                              {"m": modulo, "n": nome}).scalar()
        else:
            con.execute(sa.text(
                "UPDATE obrigacao SET periodicidade = :p, controla_imposto = :i, ativo = :t WHERE id = :id"),
                {"p": periodicidade, "i": imposto, "t": True, "id": oid})
            if imposto:
                con.execute(sa.text("UPDATE obrigacao SET descricao = :d WHERE id = :id"),
                            {"d": descricao, "id": oid})
        ids[nome] = oid
    contabeis = [r[0] for r in con.execute(sa.text("SELECT id FROM obrigacao WHERE modulo_id = :m"),
                                           {"m": modulo})]
    for regime_nome, obrigacoes in POR_REGIME.items():
        rid = con.execute(sa.text("SELECT id FROM regime_tributario WHERE nome = :n"),
                          {"n": regime_nome}).scalar()
        if rid is None:
            continue
        for oid in contabeis:  # remove os vínculos contábeis atuais (outros módulos ficam)
            con.execute(sa.text("DELETE FROM regime_obrigacao WHERE regime_id = :r AND obrigacao_id = :o"),
                        {"r": rid, "o": oid})
        for nome in obrigacoes:
            con.execute(sa.text("INSERT INTO regime_obrigacao (regime_id, obrigacao_id) VALUES (:r, :o)"),
                        {"r": rid, "o": ids[nome]})
    # Distribuição de Lucros agora tem aba própria: deixa de ser obrigação de qualquer regime.
    dist = con.execute(sa.text("SELECT id FROM obrigacao WHERE modulo_id = :m AND nome = 'Distribuição de Lucros'"),
                       {"m": modulo}).scalar()
    if dist is not None:
        con.execute(sa.text("DELETE FROM regime_obrigacao WHERE obrigacao_id = :o"), {"o": dist})
        con.execute(sa.text("UPDATE obrigacao SET ativo = :f WHERE id = :o"), {"f": False, "o": dist})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obrigacao', schema=None) as batch_op:
        batch_op.drop_column('controla_imposto')

    with op.batch_alter_table('entrega', schema=None) as batch_op:
        batch_op.drop_column('valor_quota')
        batch_op.drop_column('valor_imposto')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
